### PR TITLE
Fix usage of DisplayMetrics

### LINKED ISSUE #121: Script won't play, immediately throws error "after Resolution Change"
> MAKE SURE YOU TESTED THE LATEST RELEASE.

Using v0.12.0

> See 'SAMSUNG.md' first, if you're a Samsung user.

Done, app had been running fine previously.

**Describe the bug**
Script immediately stops after pressing play button (on support selection screen or battle screen) and throws up a bunch of code.

**Screenshots**
Screenshot_20200526-212133_Nova Launcher
Screenshot_20200526-212112_Fate_GO

**Device Info (please fill atleast 'Device model'):**
 - Device model: Samsung Galaxy S9
 - Screen size: 2960x1440
 - Android Version: Android 10
 - RAM: 4GB

### PR DESCRIPTION
**Pull request by MathewSachin**
DisplayMetrics are re-read on starting the script or dragging play button (fixes #121).

Also fixes the problem of play button not moving freely on Nox.

### CODE REVIEW

File: app/src/main/java/com/mathewsachin/fategrandautomata/accessibility/ScriptRunnerUserInterface.kt [hunk 1]
```diff
@@ -33,6 +33,29 @@ class ScriptRunnerUserInterface(val Service: ScriptRunnerService) {
...
+
+        return res
+    }
+
+    val mediaProjectionMetrics: DisplayMetrics get() {
+        val res = metrics
+
+        // Retrieve images in Landscape
+        if (res.heightPixels > res.widthPixels) {
+            res.let {
```
Comment (reconman) [inline app/src/main/java/com/mathewsachin/fategrandautomata/accessibility/ScriptRunnerUserInterface.kt:49]: Why do you even use `.let`?

Also, I searched for swapping variables in Kotlin and found this:
```
res.widthPixels = res.heightPixels.also { res.heightPixels = res.widthPixels}
```

Comment (MathewSachin) [reply app/src/main/java/com/mathewsachin/fategrandautomata/accessibility/ScriptRunnerUserInterface.kt:49]: let, also, run, apply can be used to manipulate an item without referring to it again and again by name. There are some differences like you refer the object using `it` or `this`

Swapping using also doesn't look good to me, so didn't use that. Maybe there's some other way.

File: app/src/main/java/com/mathewsachin/fategrandautomata/accessibility/ScriptRunnerUserInterface.kt [hunk 2]
```diff
@@ -33,6 +33,29 @@ class ScriptRunnerUserInterface(val Service: ScriptRunnerService) {
...
 
+    private val metrics: DisplayMetrics get() {
+        val res = DisplayMetrics()
+
+        windowManager.defaultDisplay.getRealMetrics(res)
+
+        return res
+    }
+
+    val mediaProjectionMetrics: DisplayMetrics get() {
```
Comment (reconman) [inline app/src/main/java/com/mathewsachin/fategrandautomata/accessibility/ScriptRunnerUserInterface.kt:44]: Can you add a KDoc explaining what this is used for? My assumption is that it's used to only take landscape screenshots and recordings.

File: app/src/main/java/com/mathewsachin/fategrandautomata/accessibility/ScriptRunnerUserInterface.kt [hunk 3]
```diff
@@ -112,30 +124,26 @@ class ScriptRunnerUserInterface(val Service: ScriptRunnerService) {
...
-        val rotate = rotation == Surface.ROTATION_0 || rotation == Surface.ROTATION_180
+        val m = metrics
 
-        val x = (if (rotate) {
-            metrics.heightPixels
-        } else metrics.widthPixels) - layout.measuredWidth
-        val y = (if (rotate) {
-            metrics.widthPixels
-        } else metrics.heightPixels) - layout.measuredHeight
+        val x = m.widthPixels - layout.measuredWidth
```
Comment (reconman) [inline app/src/main/java/com/mathewsachin/fategrandautomata/accessibility/ScriptRunnerUserInterface.kt:129]: Can you explain this logic? Is `layout` only the button? So if the screen is 1280 pixels wide and the button is 100 pixels wide, x == 1180?

Please add KDoc to this method.

File: app/src/main/java/com/mathewsachin/fategrandautomata/accessibility/ScriptRunnerUserInterface.kt (hunk 2 above)
Comment (MathewSachin) [reply app/src/main/java/com/mathewsachin/fategrandautomata/accessibility/ScriptRunnerUserInterface.kt:45]: Yeah, the name has `mediaProjection` in it and there's a comment inside saying about using only landscape. KDoc feels redundant, still added.

File: app/src/main/java/com/mathewsachin/fategrandautomata/accessibility/ScriptRunnerUserInterface.kt (hunk 3 above)
Comment (MathewSachin) [reply app/src/main/java/com/mathewsachin/fategrandautomata/accessibility/ScriptRunnerUserInterface.kt]: Yup, just as you thought. I don't think it was even complicated. The code before this PR was of course. I added KDoc, and also changed the name of `layout` to `scriptCtrlBtnLayout`.

File: app/src/main/java/com/mathewsachin/fategrandautomata/accessibility/ScriptRunnerUserInterface.kt (hunk 1 above)
Comment (reconman) [reply app/src/main/java/com/mathewsachin/fategrandautomata/accessibility/ScriptRunnerUserInterface.kt:50]: In my opinion, `it` is pretty ambiguous, it could mean anything, and `let` is only useful when you don't want to assign something to a variable. In this case using `res` is the same amount of effort as using `it`.

Comment (MathewSachin) [reply app/src/main/java/com/mathewsachin/fategrandautomata/accessibility/ScriptRunnerUserInterface.kt:50]: Umm, `it` isn't ambiguous. It is a convention in Kotlin. If there is only one parameter to a lambda, it's name by default is `it`.
Yeah, `run` should probably be used here in place of `let`.
The benefit of this approach is that `temp` doesn't leak out of that scope.
Another benefit I can think is if we rename `res` later to something else, maybe a longer more descriptive name, the amount of change required will be minimal.

Comment (reconman) [reply app/src/main/java/com/mathewsachin/fategrandautomata/accessibility/ScriptRunnerUserInterface.kt:50]: `temp` is also only visible inside of the `if`. I still find using `res` better, but you can merge if you want to keep `let`.

Comment (MathewSachin) [reply app/src/main/java/com/mathewsachin/fategrandautomata/accessibility/ScriptRunnerUserInterface.kt:50]: I want to keep `let` 😅
