### PR TITLE
Fix: Story Skip

### LINKED ISSUE #148: Story skip does not work
> MAKE SURE YOU TESTED THE LATEST RELEASE.

> See 'SAMSUNG.md' first, if you're a Samsung user.

**Describe the bug**
I got everything setup and it does work if I am going to farm one stage but if I set it up to go through the story stages it never presses skip and if I manually press skip it does not tap the screen when it says "Quest cleared Get reward"
**Screenshots**
If an error occurred, you can find the message by expanding the app's notification.
It is recommended that you atleast add one screenshot of FGO running on your device.

**Video**
If relevant, include a video of the script running on your device with `Debug mode` ON (recording functionality is available within the app in `More options`).

**Device Info (please fill atleast 'Device model'):**
Bluestacks, rooted

### PR DESCRIPTION
**Pull request by MathewSachin**
fixes #148 

OpenCV release v4.4 which adds support for matching transparent images.
So, we can now reliably match Story Skip image which needs to be transparent.

I've added Story Skip check to the outer loop so it doesn't matter whenever it comes up it can get matched.

I was getting around 0.77 similarity when matching, and 0.44 when not matching, so I've set the similarity at 0.7.

After this PR is merged, I plan to take more things out of the `result` function. Specifically, I want to make the app respond faster to the free quest repeat dialog.

### CODE REVIEW

File: scripts/src/main/java/com/mathewsachin/fategrandautomata/scripts/entrypoints/AutoBattle.kt [hunk 1]
```diff
@@ -188,17 +189,7 @@ open class AutoBattle(
...
-                0.5.seconds.wait()
-                game.menuStorySkipYesClick.click()
-            }
-        }
-
-        10.seconds.wait()
-
+        // TODO: Move to outer loop
         // Quest Completion reward. Exits the screen when it is presented.
         if (game.resultCeRewardRegion.exists(images.bond10Reward)) {
```
Comment (reconman) [inline scripts/src/main/java/com/mathewsachin/fategrandautomata/scripts/entrypoints/AutoBattle.kt:194]: Hold on, why is Bond 10 handled twice? One time above, one time below?

File: app/src/main/java/com/mathewsachin/fategrandautomata/imaging/DroidCvPattern.kt [hunk 2]
```diff
@@ -75,9 +92,23 @@ class DroidCvPattern(private var Mat: Mat? = Mat(), private val OwnsMat: Boolean
             val result = DisposableMat()
 
             if (Template.width <= width && Template.height <= height) {
-                Imgproc.matchTemplate(Mat, Template.Mat, result.Mat, Imgproc.TM_CCOEFF_NORMED)
-            }
-            else logd("Skipped matching $Template: Region out of bounds")
+                alpha.let { mask ->
```
Comment (reconman) [inline app/src/main/java/com/mathewsachin/fategrandautomata/imaging/DroidCvPattern.kt:95]: Doesn't this let only create an alias for the `alpha` variable?

Why not use alpha directly?

File: app/src/main/java/com/mathewsachin/fategrandautomata/imaging/DroidCvPattern.kt [hunk 3]
```diff
@@ -75,9 +92,23 @@ class DroidCvPattern(private var Mat: Mat? = Mat(), private val OwnsMat: Boolean
...
+                    if (mask != null) {
+                        Imgproc.matchTemplate(
+                            Mat,
+                            Template.Mat,
+                            result.Mat,
+                            Imgproc.TM_CCOEFF_NORMED,
+                            mask
+                        )
+                    } else Imgproc.matchTemplate(
```
Comment (reconman) [inline app/src/main/java/com/mathewsachin/fategrandautomata/imaging/DroidCvPattern.kt:104]: To keep the if and else similar, I would add curly braces here too.

File: app/src/main/java/com/mathewsachin/fategrandautomata/imaging/DroidCvPattern.kt [hunk 4]
```diff
@@ -12,19 +12,36 @@ import java.io.InputStream
...
+                } else null
+
+                Imgproc.cvtColor(decoded, decoded, Imgproc.COLOR_RGBA2GRAY)
+
+                return MatWithAlpha(decoded, alphaChannel)
             }
         }
     }
 
+    private constructor(matWithAlpha: MatWithAlpha) : this(matWithAlpha.mat) {
```
Comment (reconman) [inline app/src/main/java/com/mathewsachin/fategrandautomata/imaging/DroidCvPattern.kt:41]: Is there any situation where we would have a constructor call with MatWithAlpha and ownsMat = false? ownsMat is part of the default constructor.

File: scripts/src/main/java/com/mathewsachin/fategrandautomata/scripts/entrypoints/AutoBattle.kt (hunk 1 above)
Comment (MathewSachin) [reply scripts/src/main/java/com/mathewsachin/fategrandautomata/scripts/entrypoints/AutoBattle.kt:194]: IIRC, this was for the CE rewards after battle

Comment (reconman) [reply scripts/src/main/java/com/mathewsachin/fategrandautomata/scripts/entrypoints/AutoBattle.kt:194]: I see, so bond10Reward is used for both. But this code won't work anymore anyways because of timing issues.

File: app/src/main/java/com/mathewsachin/fategrandautomata/imaging/DroidCvPattern.kt (hunk 2 above)
Comment (MathewSachin) [reply app/src/main/java/com/mathewsachin/fategrandautomata/imaging/DroidCvPattern.kt:95]: Because, it is a global variable, once you've checked for null, you can't be sure in the next line that it won't be set null again.

File: app/src/main/java/com/mathewsachin/fategrandautomata/imaging/DroidCvPattern.kt (hunk 4 above)
Comment (MathewSachin) [reply app/src/main/java/com/mathewsachin/fategrandautomata/imaging/DroidCvPattern.kt:41]: `ownsMat` is only used for screenshots where alpha doesn't matter

File: app/src/main/java/com/mathewsachin/fategrandautomata/imaging/DroidCvPattern.kt (hunk 2 above)
Comment (reconman) [reply app/src/main/java/com/mathewsachin/fategrandautomata/imaging/DroidCvPattern.kt:95]: You're not checking for null. Normally you would use `let` this way:
`nullable?.let {}`

File: scripts/src/main/java/com/mathewsachin/fategrandautomata/scripts/entrypoints/AutoBattle.kt (hunk 1 above)
Comment (MathewSachin) [reply scripts/src/main/java/com/mathewsachin/fategrandautomata/scripts/entrypoints/AutoBattle.kt:194]: yeah, that is why I added that TODO there

Comment (MathewSachin) [reply scripts/src/main/java/com/mathewsachin/fategrandautomata/scripts/entrypoints/AutoBattle.kt:194]: I don't think it would have worked reliably before

File: app/src/main/java/com/mathewsachin/fategrandautomata/imaging/DroidCvPattern.kt (hunk 2 above)
Comment (MathewSachin) [reply app/src/main/java/com/mathewsachin/fategrandautomata/imaging/DroidCvPattern.kt:95]: I'm checking for `null` inside `let`. Maybe try compiling yourself to get the intuition.

Comment (MathewSachin) [reply app/src/main/java/com/mathewsachin/fategrandautomata/imaging/DroidCvPattern.kt:95]: Ok. my fault. OpenCV doesn't care about null 🤦

Comment (MathewSachin) [reply app/src/main/java/com/mathewsachin/fategrandautomata/imaging/DroidCvPattern.kt]: removed the `let`.

File: app/src/main/java/com/mathewsachin/fategrandautomata/imaging/DroidCvPattern.kt (hunk 3 above)
Comment (MathewSachin) [reply app/src/main/java/com/mathewsachin/fategrandautomata/imaging/DroidCvPattern.kt]: done
