### PR TITLE
Fix: Friend lock can cause Support Servant matching to fail

### LINKED ISSUE #157: Friend lock can cause Support Servant matching to fail
With the Engine Update, Friends can be locked. That causes a lock icon to appear on the servant image in support selection screen.
This would cause matching accuracy to fall possibly causing matching to fail.
friend lock

Support Image Maker should be updated for servant images (crop a bit more from left)
AND
Support servant images here should be cropped from left:
https://github.com/MathewSachin/Fate-Grand-Automata/tree/master/app/src/main/assets/Support/servant

### PR DESCRIPTION
**Pull request by MathewSachin**
If you lock your friends, a lock icon shows on the left of servant image, which can cause matching to fail.

Instead of modifying in-built images and Support Image Maker, which would need everyone to regenerate their images,
we crop out the part which can potentially have the lock.

fixes #157

### CODE REVIEW

File: app/src/main/java/com/mathewsachin/fategrandautomata/scripts/modules/Support.kt [hunk 1]
```diff
@@ -248,13 +248,27 @@ class Support {
...
 
             for (servant in Game.SupportListRegion.findAll(pattern)) {
                 yield(servant.Region)
             }
         }
     }
 
+    /**
+     * If you lock your friends, a lock icon shows on the left of servant image,
+     * which can cause matching to fail.
```
Comment (reconman) [inline app/src/main/java/com/mathewsachin/fategrandautomata/scripts/modules/Support.kt:261]:
```suggestion
     * which can cause matching to fail.
     *
```

File: app/src/main/java/com/mathewsachin/fategrandautomata/scripts/modules/Support.kt [hunk 2]
```diff
@@ -248,13 +248,27 @@ class Support {
...
+     * Instead of modifying in-built images and Support Image Maker,
+     * which would need everyone to regenerate their images,
+     * crop out the part which can potentially have the lock.
+     */
+    private fun IPattern.cropFriendLock(): IPattern {
```
Comment (reconman) [inline app/src/main/java/com/mathewsachin/fategrandautomata/scripts/modules/Support.kt:266]: I feel like this method is a bit dangerous to be declared on IPattern. You don't want to execute this code for any random image, just for servant images. And you also don't want to execute this multiple times in a row.
